# vim: tabstop=4:softtabstop=4:shiftwidth=4:noexpandtab
# Makefile template

THISPATH=`pwd`
THISPROJECT=`basename $THISPATH`
THISDATE=`date`


all: init scripts
	@echo "* Compiled all targets for $(THISPROJECT) project."
	@exit 0

scripts: init src/template.projectsync-project src/template.project-sync-to-remotehost
	@build.sh
	@echo "* Build finished: 'scripts'" 
	@exit 0

init:
## 	misc configuration/autogenerated code goes here
	@exit 0


clean: 
##	@if [ -f build/$(INIREAD) ]; then  rm "build/$(INIREAD)"; echo "* Removed $(INIREAD)"; fi
##	@if [ -f build/$(INIWRITE) ]; then  rm "build/$(INIWRITE)"; echo "* Removed $(INIWRITE)"; fi
###	@if [ -f build/git-getdescription ]; then rm build/git-getdescription; echo "removed git-getdescription"; fi
	@echo "\n* Cleaned all built files."
	@exit 0

#.PHONY: test help


